version: '3.3'
services:
  app:
    build: .
    environment:
      RAILS_ENV: development
      MYSQL_ROOT_PASSWORD: 'pass'
      DATABASE_URL: mysql2://root:pass@db:3306
    ports:
      - '3000:3000'
    volumes:
      - .:/sample_app
      - ./vendor/bundle:/sample_app/vendor/bundle:delegated
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    volumes:
      - ./tmp/db:/var/lib/mysql
    ports:
      - '3306:3306'
