# mysql2 を利用する
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  socket: /tmp/mysql.sock
  port: 3306
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test

production:
  <<: *default
  database: sample_app_production
